LogisticApp/ViewModels/OrderViewModel.cs
namespace LogisticApp.ViewModels
{
    public class OrderViewModel
    {
        public string SenderCityName {  get; set; }
        public string SenderFullInCityAddress {  get; set; }

        public string RecipientCityName { get; set; }
        public string RecipientFullInCityAddress { get; set; }

        public DateTime CreationDtm { get; set; }
        public float CargoWeightInKilograms { get; set; }

    }

}

LogisticApp/Controllers/DetailedOrderController.cs
using LogisticApp.Model;
using Microsoft.AspNetCore.Mvc;

namespace LogisticApp.Controllers
{
    public class DetailedOrderController : Controller
    {
        private readonly LogisticAppContext _context;
        public DetailedOrderController(LogisticAppContext context)
        {
            _context = context;
        }
        public IActionResult Index(string orderId)
        {
            Order clickedOrder = _context.Orders.Single(o => o.Id == Guid.Parse(orderId));
            ViewBag.CurrentOrder = clickedOrder;
            return View("~/Views/DetailedOrder.cshtml");
        }
    }
}

LogisticApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace LogisticApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

LogisticApp/Controllers/OrderFormController.cs
using LogisticApp.Model;
using LogisticApp.ViewModels;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Specialized;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;

namespace LogisticApp.Controllers
{
    public class OrderFormController : Controller
    {
        private readonly LogisticAppContext _context;
        public OrderFormController(LogisticAppContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View("~/Views/OrderForm.cshtml");
        }

        [HttpGet]
        public IActionResult GetSuggestedCities()
        {
            string cityName = HttpContext.Request.Query["term"].ToString();
            var suggestedNames = _context.Cities
                .Where(c => EF.Functions.Like(c.Name, $"%{cityName}%"))
                .Select(c => c.Name).ToList();


            return Ok(suggestedNames);
        }

        [HttpGet]
        public IActionResult GetSuggestedAddresses()
        {
            NameValueCollection test = HttpUtility.ParseQueryString(HttpContext.Request.QueryString.ToString());
            string? cityName = test["city"];
            //if (cityName == null)
            //not ok

            string? inputAddress = test["address"];

            List<City> cities = _context.Cities
            .Where(c => EF.Functions.Like(c.Name, $"%{cityName}%"))
            .ToList();

            List<string> allAddresses = new List<string>();
            foreach (City city in cities)
            {
                foreach (Street street in city.Streets)
                {
                    foreach (House house in street.Houses)
                    {
                         allAddresses.Add(house.BuildFullAddress());
                    }
                }
            }

            List<string> suggestedAddresses = allAddresses
                .Where(fullAddressString => Regex.IsMatch(fullAddressString, @"" + inputAddress, RegexOptions.IgnoreCase))
                .ToList();

            return Ok(suggestedAddresses);
        }

        [HttpPost]
        public IActionResult CreateOrder(OrderViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            Dictionary<string, string>? senderAddressComponents = Address.SplitInCityAddressString(model.SenderFullInCityAddress);
            Dictionary<string, string>? recipientAddressComponents = Address.SplitInCityAddressString(model.RecipientFullInCityAddress);
            
            Postcode senderPostcode;
            Postcode recipientPostcode;
            try
            {
                senderPostcode = _context.Postcodes.Single(pc => pc.Code == senderAddressComponents["postcode"]);
                recipientPostcode = _context.Postcodes.Single(pc => pc.Code == recipientAddressComponents["postcode"]);
            }
            catch (Exception ex)
            {
                return BadRequest();
            }

            Address senderAddress = new Address(senderPostcode, senderAddressComponents["house"]);
            Address recipientAddress = new Address(recipientPostcode, recipientAddressComponents["house"]);

            Order order = new Order
            {
                SenderAddressId = senderAddress.Id,
                RecipientAddressId = recipientAddress.Id,
                CreationDtm = model.CreationDtm.ToUniversalTime(),
                DisplayId = $"O-{1000 + _context.Orders.Count()}",
                CargoWeightInGrams = (int)(model.CargoWeightInKilograms * 1000)
            };

            _context.Addresses.Add(senderAddress);
            _context.Addresses.Add(recipientAddress);
            _context.Orders.Add(order);
            _context.SaveChanges();

            return View("~/Views/Home/Index.cshtml");
        }
    }
}

LogisticApp/Controllers/OrderListController.cs
using LogisticApp.Model;
using Microsoft.AspNetCore.Mvc;

namespace LogisticApp.Controllers
{
    public class OrderListController : Controller
    {
        private readonly LogisticAppContext _context;
        public OrderListController(LogisticAppContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            ViewBag.Orders = _context.Orders.ToList();
            return View("~/Views/OrderList.cshtml");
        }
    }
}

LogisticApp/Views/DetailedOrder.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@using LogisticApp.Model

@{
    Layout = "_Layout";
    Order currOrder = ViewBag.CurrentOrder;
    Address sender = currOrder.SenderAddress;
    Address recipient = currOrder.RecipientAddress;
}

<div class="maximized_order">
    <div class="order_header">
        <label id="maximized_order_header_label">НОМЕР ЗАКАЗА:</label>
        <p id="maximized_order_display_id">@currOrder.DisplayId</p>
    </div>

    <div class="order_fields_wrapper">

        <div class="maximized_order_address_wrapper">
            <label class="minimized_order_label">Адрес отправителя</label>
            <div class="maximized_order_address">
                <label>Город:</label>
                <p>@sender.City.Name</p>
                <br>
                <label>@sender.Street.StreetType.Name:</label>
                <p>@sender.Street.Name</p>
                <br>
                <label>Дом:</label>
                <p>@sender.House.Number</p>
                <br>
                <label>Почтовый индекс:</label>
                <p>@sender.House.Postcode.Code</p>
            </div>
        </div>

        <div class="maximized_order_address_wrapper">
            <label class="minimized_order_label">Адрес отправителя</label>
            <div class="maximized_order_address">
                <label>Город:</label>
                <p>@recipient.City.Name</p>
                <br>
                <label>@recipient.Street.StreetType.Name:</label>
                <p>@recipient.Street.Name</p>
                <br>
                <label>Дом:</label>
                <p>@recipient.House.Number</p>
                <br>
                <label>Почтовый индекс:</label>
                <p>@recipient.House.Postcode.Code</p>
            </div>
        </div>

        <div>
            <label class="minimized_order_label">Дата и время создания:</label>
            <p class="minimized_order_field">@currOrder.CreationDtm.ToLocalTime().ToString("dd.MM.yyyy HH:mm")</p>
        </div>

        <div>
            <label class="minimized_order_label">Вес груза (кг.):</label>
            <p class="minimized_order_field">@(currOrder.CargoWeightInGrams / 1000f)</p>
        </div>
    </div>
</div>

LogisticApp/Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layout";
}

LogisticApp/Views/OrderForm.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    Layout = "_Layout";
}

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model LogisticApp.ViewModels.OrderViewModel

<form method="post" id="order-creation-form" action="@Url.Action("CreateOrder", "OrderForm")">
    <label>Отправитель</label>
    <div class="address">
        <div>
            <label>Город:</label>
            <input type="text" class="city_input" asp-for="SenderCityName" required />
            <span asp-validation-for="SenderCityName"></span>
        </div>
        <div>
            <label>Адрес:</label>
            <input type="text" class="address_input" asp-for="SenderFullInCityAddress" required />
            <span asp-validation-for="SenderFullInCityAddress"></span>
        </div>
    </div>
    <label>Получатель</label>
    <div class="address">
        <div>
            <label>Город:</label>
            <input type="text" class="city_input" asp-for="RecipientCityName" required />
            <span asp-validation-for="RecipientCityName"></span>
        </div>
        <div>
            <label>Адрес:</label>
            <input type="text" class="address_input" asp-for="RecipientFullInCityAddress" required />
            <span asp-validation-for="RecipientFullInCityAddress"></span>
        </div>
    </div>

    <label>Вес груза в килограммах:</label>
    <div>
        <input type="number" step="0.01" asp-for="CargoWeightInKilograms" required />
        <span asp-validation-for="CargoWeightInKilograms"></span>
    </div>

    <label>Дата создания заказа:</label>
    <div>
        <input type="datetime-local" asp-for="CreationDtm" required/>
        <span asp-validation-for="CreationDtm"></span>
    </div>

    <input type="submit" value="Создать" />
</form>

@section Scripts {
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="~/js/autocomplete.js"></script>
}

LogisticApp/Views/OrderList.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@using LogisticApp.Model

@{
    Layout = "_Layout";
    List<Order> orders = ViewBag.Orders;
    orders.Sort((x, y) => x.DisplayId.CompareTo(y.DisplayId));
}

<section id="allorders">
    @{
        foreach (Order order in orders)
        {
            Address sender = order.SenderAddress;
            Address recipient = order.RecipientAddress;
            string id = order.Id.ToString();
            <a href="@Url.Action("Index", "DetailedOrder", new {orderId = id})">
                <div class="minimized_order">
                    <p class="order_display_id">@order.DisplayId</p>
                    <div class="order_fields_wrapper">
                        <label class="minimized_order_label">Адрес отправителя:</label>
                        <p class="minimized_order_field">г. @sender.City.Name @sender.Street.StreetType.Name @sender.Street.Name д. @sender.House.Number, @sender.House.Postcode.Code</p>
                        <label class="minimized_order_label">Адрес получателя:</label>
                        <p class="minimized_order_field">г. @recipient.City.Name @recipient.Street.StreetType.Name @recipient.Street.Name д. @recipient.House.Number, @recipient.House.Postcode.Code</p>
                        <label class="minimized_order_label">Дата и время создания:</label>
                        <p class="minimized_order_field"> @order.CreationDtm.ToLocalTime().ToString("dd.MM.yyyy HH:mm")</p>
                        <label class="minimized_order_label">Вес груза (кг.):</label>
                        <p class="minimized_order_field">@(order.CargoWeightInGrams / 1000f)</p>
                    </div>
                </div>
            </a>
            
        }
    }
</section>

LogisticApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="~/css/layout.css" />
    <link rel="stylesheet" type="text/css" href="~/css/form.css" />
    <link rel="stylesheet" type="text/css" href="~/css/order_list.css" />
    <link rel="stylesheet" type="text/css" href="~/css/detailed_order.css" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <header>
        <h1> Приёмка заказов на доставку </h1>
        <nav id="site-navigation">
            <a href="@Url.Action("Index", "OrderList")">Все заказы</a>
            <a href="@Url.Action("Index", "OrderForm")">Создать заказ</a>
        </nav>
    </header>

    @RenderBody()
</body>

@RenderSection("Scripts", false)

</html>